### ISSUE TITLE
Print library output

### ISSUE THREAD

**Issue by KLupa** [thirdorange/Karafin_CSCI2270_FinalProject#1]
When the 'Print all titles in library' option is chosen, it outputs all of the movie titles correctly, however one of them includes the author and category, while the rest only display the title. The particular book that includes the extra info sometimes changes when a new book is added, but sometimes it does not. It begins with the first book entered.

**Comment by thirdorange** [comment]
Updated the console output for the recursive call of printLibrary method so that the correct information is displayed for all books in the library.
